 

--  Implementation of traderbots for EXPRES.

package Sancta.Traderbot_Types is

   pragma Preelaborate;

   Log_Section    : constant String := "sancta.traderbot_types";
   Detail_Section : constant String := "sancta.traderbot_types.detail";
   --  To selectively enable debug messages...

   type Auction_Task_Policies is record
      First                    : Boolean := False;
      Second                   : Boolean := True;
      All_But_First_And_Second : Boolean := True;
      Generated                : Boolean := True;
      Added                    : Boolean := False;
      Won                      : Boolean := False;
   end record;
   --  What task will be auctioned at the actioning time.
   --  Generated: Tasks generated by normal operation.
   --  Added: tasks received from operator.
   --  Won: tasks won in auction.

   Default_Auction_Task_Policy : constant Auction_Task_Policies :=
                                   (First                    => False,
                                    Second                   => True,
                                    All_But_First_And_Second => True,
                                    Generated                => True,
                                    Added                    => False,
                                    Won                      => False);

   type Auction_Time_Policies is record
      Auction_On_Adition      : Boolean  := True; -- When a task is added manually.
      Auction_On_Finalization : Boolean  := True; -- When a task is finished.
      Periodic                : Duration := Duration'Last;
   end record;
   --  When to start an auction

   Default_Auction_Time_Policy : constant Auction_Time_Policies :=
                                   (Auction_On_Adition      => True,
                                    Auction_On_Finalization => True,
                                    Periodic                => Duration'Last);

   --  If Added, just the Added will be auctioned.
   --  If not Added and Auction_On_Addition, all the tasks will be auctioned.

   type Insertion_Policies is (First, Last, Best);
   --  A new task is added to the first, last or best position.
   --  Best causes (|T| + 1) Task-to-Task costs to be evaluated.

end Sancta.Traderbot_Types;
