#!/bin/bash

ids="ari ben ced dan epi fio zak"
ids_enabled="ari ben ced dan epi fio zak"
ids_enabled="ari ben zak"
ids_poweroff="x"

pcommon="--config sancta.xml --nodes ari.ben.ced.dan.epi.fio.zak "
pcommon="--config sancta.xml --nodes ari.ben.zak "
params="  $pcommon --playerport 7770" 	# ARI
params+=",$pcommon --playerport 7771" 	# BEN
params+=",$pcommon --playerport 7772" 	# CED
params+=",$pcommon --playerport 7773" 	# DAN
params+=",$pcommon --playerport 7774" 	# EPI
params+=",$pcommon --playerport 7775" 	# FIO
params+=",$pcommon --playerport 7780" 	# ZAK

master=.
remotes="ct.ari ct.ben ct.ced ct.dan ct.epi ct.fio ct.zak"

exes="node_gtk node_gtk node_gtk node_gtk node_gtk node_gtk node_gtk"
modes="x x x x x x x"
excludes="node node node node node node node"

xterm_profile="" #"--window-with-profile Default"
gp="--geometry="
gs="80x24"
geoms="$gp$gs+0+0 $gp$gs+665+0 $gp$gs+0+462 $gp$gs+665+462 $gp$gs+615+505 $gp$gs+0+0 $gp$gs+665+0"

environment="PATH=$HOME/local/bin:.:$PATH ; ulimit -s unlimited ; export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH"
procs="node node_gtk gnome-terminal sleep player"

laplogins="localhost localhost localhost localhost localhost localhost localhost"
lapports="22 22 22 22 22 22 22"
laplisten="2222 2223 2224 2225 2226 2227 2228"
botlogins="localhost localhost localhost localhost localhost localhost localhost"
botports="22 22 22 22 22 22 22"
