car (
   color "green"
   pose [-36.8 -22.85 -2.71]
   bitmap "../../cars/car1.png"
)

car (
   color "VioletRed1"
   pose [-37.16 -10.98 2.67]
   bitmap "../../cars/car4.png"
)

car (
   color "red"
   pose [-37.03 -6.18 -1.05]
   bitmap "../../cars/car2.png"
)

car (
   color "green"
   pose [-36.89 6.17 1.96]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [-37.17 10.95 -2.6]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [-36.86 22.92 -0.42]
   bitmap "../../cars/car4.png"
)

car (
   color "VioletRed1"
   pose [-34.17 -23.05 2.32]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-34.06 -10.95 -0.66]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkSlateGray"
   pose [-33.92 -5.92 -1.28]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [-33.99 6.16 -1.23]
   bitmap "../../cars/car4.png"
)

car (
   color "SteelBlue1"
   pose [-33.97 11.15 -0.93]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrchid1"
   pose [-34.07 23.09 1.37]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrchid1"
   pose [-30.99 -23.07 -2.96]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkCyan"
   pose [-30.91 -10.98 -2.86]
   bitmap "../../cars/car4.png"
)

car (
   color "turquoise1"
   pose [-31.13 -5.83 2.58]
   bitmap "../../cars/car1.png"
)

car (
   color "pink1"
   pose [-30.95 6.03 1.12]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-31.09 10.81 1.04]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-31.13 22.84 2.27]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-27.83 -23.07 0.76]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [-27.87 -10.83 2.43]
   bitmap "../../cars/car3.png"
)

car (
   color "navy"
   pose [-28.02 -5.92 1.97]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [-28.05 6.05 0.49]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [-27.87 11.14 1.64]
   bitmap "../../cars/car3.png"
)

car (
   color "turquoise1"
   pose [-28.15 22.8 -1.02]
   bitmap "../../cars/car1.png"
)

car (
   color "SeaGreen"
   pose [-25.05 -22.87 2.83]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-25.15 -10.93 -0.25]
   bitmap "../../cars/car3.png"
)

car (
   color "chocolate1"
   pose [-25.16 -6.18 -0.32]
   bitmap "../../cars/car5.png"
)

car (
   color "turquoise1"
   pose [-25.11 5.86 1.14]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkBlue"
   pose [-25.0 10.96 -1.98]
   bitmap "../../cars/car2.png"
)

car (
   color "DeepSkyBlue1"
   pose [-24.95 22.94 -0.96]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-22.04 -22.89 -2.24]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkRed"
   pose [-21.96 -11.06 2.24]
   bitmap "../../cars/car2.png"
)

car (
   color "black"
   pose [-21.97 -5.85 0.84]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [-21.82 6.2 2.67]
   bitmap "../../cars/car3.png"
)

car (
   color "magenta1"
   pose [-21.95 10.83 -2.7]
   bitmap "../../cars/car2.png"
)

car (
   color "green"
   pose [-22.03 22.88 -1.29]
   bitmap "../../cars/car1.png"
)

car (
   color "DeepSkyBlue1"
   pose [-18.86 -22.9 2.9]
   bitmap "../../cars/car5.png"
)

car (
   color "black"
   pose [-19.11 -10.91 -1.56]
   bitmap "../../cars/car1.png"
)

car (
   color "aquamarine4"
   pose [-19.1 -5.87 -0.97]
   bitmap "../../cars/car1.png"
)

car (
   color "red"
   pose [-18.97 5.98 -0.4]
   bitmap "../../cars/car2.png"
)

car (
   color "navy"
   pose [-19.0 11.04 2.63]
   bitmap "../../cars/car1.png"
)

car (
   color "cyan1"
   pose [-19.16 23.06 0.63]
   bitmap "../../cars/car2.png"
)

car (
   color "black"
   pose [-15.82 -22.91 -1.52]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkOrchid1"
   pose [-16.02 -11.09 -2.97]
   bitmap "../../cars/car3.png"
)

car (
   color "aquamarine4"
   pose [-16.09 -6.03 1.27]
   bitmap "../../cars/car2.png"
)

car (
   color "aquamarine4"
   pose [-16.04 6.16 -1.29]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkSlateGray"
   pose [-16.06 10.82 2.17]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [-15.8 22.95 2.35]
   bitmap "../../cars/car2.png"
)

car (
   color "red"
   pose [-13.08 -22.85 -0.96]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [-13.04 -10.83 1.73]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-13.03 -6.01 -1.54]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrchid1"
   pose [-12.82 5.82 -1.01]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrchid1"
   pose [-12.91 10.83 2.83]
   bitmap "../../cars/car2.png"
)

car (
   color "green"
   pose [-12.94 22.9 0.33]
   bitmap "../../cars/car5.png"
)

car (
   color "aquamarine4"
   pose [-10.19 -22.99 -0.16]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [-10.0 -10.91 -0.22]
   bitmap "../../cars/car1.png"
)

car (
   color "cyan1"
   pose [-10.13 -6.07 -1.68]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [-9.82 5.94 -2.88]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [-9.92 11.17 -0.04]
   bitmap "../../cars/car4.png"
)

car (
   color "cyan1"
   pose [-9.85 23.11 -2.96]
   bitmap "../../cars/car3.png"
)

car (
   color "black"
   pose [-6.93 -23.07 0.93]
   bitmap "../../cars/car2.png"
)

car (
   color "magenta1"
   pose [-6.91 -10.82 0.87]
   bitmap "../../cars/car3.png"
)

car (
   color "maroon1"
   pose [-7.17 -6.13 -1.9]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-7.12 5.93 2.91]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [-7.02 11.07 2.89]
   bitmap "../../cars/car4.png"
)

car (
   color "aquamarine4"
   pose [-6.97 22.84 1.39]
   bitmap "../../cars/car2.png"
)

car (
   color "chocolate1"
   pose [-3.93 -23.12 1.21]
   bitmap "../../cars/car4.png"
)

car (
   color "red"
   pose [-4.03 -11.07 -1.79]
   bitmap "../../cars/car2.png"
)

car (
   color "turquoise1"
   pose [-3.83 -5.95 2.76]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [-3.84 5.9 2.77]
   bitmap "../../cars/car5.png"
)

car (
   color "chocolate1"
   pose [-3.86 10.92 1.09]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkRed"
   pose [-4.1 23.03 1.71]
   bitmap "../../cars/car3.png"
)

car (
   color "turquoise1"
   pose [-1.18 -23.02 0.66]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkSlateGray"
   pose [-0.88 -10.93 -0.62]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-0.85 -5.94 0.43]
   bitmap "../../cars/car1.png"
)

car (
   color "maroon1"
   pose [-0.93 5.88 -1.66]
   bitmap "../../cars/car5.png"
)

car (
   color "blue"
   pose [-1.1 11.06 0.37]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [-1.07 23.18 -0.45]
   bitmap "../../cars/car1.png"
)

car (
   color "green"
   pose [1.9 -22.92 -0.61]
   bitmap "../../cars/car4.png"
)

car (
   color "red"
   pose [1.91 -11.17 -0.68]
   bitmap "../../cars/car4.png"
)

car (
   color "aquamarine4"
   pose [2.19 -6.07 0.32]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkMagenta"
   pose [1.86 5.84 -2.86]
   bitmap "../../cars/car2.png"
)

car (
   color "maroon1"
   pose [2.05 11.13 1.68]
   bitmap "../../cars/car1.png"
)

car (
   color "turquoise1"
   pose [2.05 23.05 0.18]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrange"
   pose [5.09 -22.91 2.69]
   bitmap "../../cars/car1.png"
)

car (
   color "navy"
   pose [5.02 -11.03 0.73]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkOrchid1"
   pose [4.83 -6.06 1.81]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkRed"
   pose [4.91 6.05 1.04]
   bitmap "../../cars/car2.png"
)

car (
   color "maroon4"
   pose [5.08 11.0 -2.84]
   bitmap "../../cars/car2.png"
)

car (
   color "green"
   pose [4.99 22.91 2.71]
   bitmap "../../cars/car1.png"
)

car (
   color "VioletRed1"
   pose [8.04 -22.83 2.64]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkOrange"
   pose [7.8 -11.16 -2.37]
   bitmap "../../cars/car1.png"
)

car (
   color "turquoise1"
   pose [8.08 -5.92 -0.93]
   bitmap "../../cars/car4.png"
)

car (
   color "SeaGreen"
   pose [8.12 6.13 1.7]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkSlateGray"
   pose [8.13 11.13 2.28]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [7.92 23.01 -1.67]
   bitmap "../../cars/car4.png"
)

car (
   color "pink1"
   pose [11.03 -23.05 2.65]
   bitmap "../../cars/car4.png"
)

car (
   color "SeaGreen"
   pose [10.85 -11.07 -2.79]
   bitmap "../../cars/car2.png"
)

car (
   color "blue"
   pose [10.92 -6.14 -2.07]
   bitmap "../../cars/car5.png"
)

car (
   color "cyan1"
   pose [11.02 6.07 -0.68]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkCyan"
   pose [11.2 10.88 -0.97]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [11.18 22.81 -1.52]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [14.15 -22.88 -2.16]
   bitmap "../../cars/car2.png"
)

car (
   color "DeepSkyBlue1"
   pose [14.11 -11.0 1.42]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkBlue"
   pose [14.13 -6.14 1.93]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrchid1"
   pose [13.84 6.06 -2.53]
   bitmap "../../cars/car1.png"
)

car (
   color "SteelBlue1"
   pose [14.05 11.05 -1.99]
   bitmap "../../cars/car5.png"
)

car (
   color "cyan1"
   pose [14.17 22.83 -0.92]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkRed"
   pose [17.01 -22.85 -1.61]
   bitmap "../../cars/car2.png"
)

car (
   color "cyan1"
   pose [16.81 -11.17 1.9]
   bitmap "../../cars/car3.png"
)

car (
   color "red"
   pose [17.1 -6.17 -0.22]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkGreen"
   pose [16.98 6.14 1.47]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [17.06 10.9 -2.85]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [17.08 22.83 1.52]
   bitmap "../../cars/car3.png"
)

car (
   color "SeaGreen"
   pose [19.92 -23.04 -2.35]
   bitmap "../../cars/car5.png"
)

car (
   color "magenta1"
   pose [19.81 -10.89 0.44]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkGreen"
   pose [19.82 -6.16 -1.76]
   bitmap "../../cars/car4.png"
)

car (
   color "magenta1"
   pose [20.08 6.01 0.02]
   bitmap "../../cars/car1.png"
)

car (
   color "SteelBlue1"
   pose [20.13 10.81 -0.46]
   bitmap "../../cars/car4.png"
)

car (
   color "green"
   pose [20.17 23.0 1.34]
   bitmap "../../cars/car1.png"
)

car (
   color "VioletRed1"
   pose [23.15 -22.84 -0.49]
   bitmap "../../cars/car2.png"
)

car (
   color "SeaGreen"
   pose [23.02 -10.83 1.42]
   bitmap "../../cars/car5.png"
)

car (
   color "blue"
   pose [23.03 -6.04 1.87]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkOrange"
   pose [22.99 5.89 2.85]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkRed"
   pose [23.2 11.0 0.8]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [23.15 23.07 -1.25]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [26.06 -22.89 -2.82]
   bitmap "../../cars/car4.png"
)

car (
   color "blue"
   pose [26.17 -11.05 -0.07]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkOrchid1"
   pose [26.08 -5.91 -0.32]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkSlateGray"
   pose [26.16 5.85 1.12]
   bitmap "../../cars/car5.png"
)

car (
   color "magenta1"
   pose [25.82 11.14 -1.31]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [25.95 23.18 1.07]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [29.1 -23.1 0.96]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkMagenta"
   pose [29.03 -11.13 1.55]
   bitmap "../../cars/car4.png"
)

car (
   color "chocolate1"
   pose [29.17 -6.11 0.41]
   bitmap "../../cars/car1.png"
)

car (
   color "red"
   pose [29.12 5.82 -1.38]
   bitmap "../../cars/car2.png"
)

car (
   color "blue"
   pose [29.01 11.2 -0.62]
   bitmap "../../cars/car4.png"
)

car (
   color "cyan1"
   pose [29.03 22.85 0.59]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkCyan"
   pose [40.9 -14.19 -90.04]
   bitmap "../../cars/car3.png"
)

car (
   color "chocolate1"
   pose [41.11 -10.97 -92.54]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrchid1"
   pose [41.05 -8.11 -89.91]
   bitmap "../../cars/car3.png"
)

car (
   color "navy"
   pose [41.11 -4.81 -89.71]
   bitmap "../../cars/car4.png"
)

car (
   color "SeaGreen"
   pose [40.98 -1.89 -88.07]
   bitmap "../../cars/car5.png"
)

car (
   color "navy"
   pose [41.15 1.13 -91.01]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [41.13 4.06 -89.87]
   bitmap "../../cars/car4.png"
)

car (
   color "SteelBlue1"
   pose [41.04 6.87 -92.13]
   bitmap "../../cars/car3.png"
)

car (
   color "cyan1"
   pose [40.87 9.96 -89.12]
   bitmap "../../cars/car5.png"
)

car (
   color "DeepSkyBlue1"
   pose [40.94 13.09 -89.49]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkOrchid1"
   pose [41.04 15.81 -89.69]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkBlue"
   pose [40.91 19.01 -92.03]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkOrange"
   pose [40.97 22.15 -91.18]
   bitmap "../../cars/car5.png"
)

