car (
   color "green"
   pose [-37.0 -23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DeepSkyBlue1"
   pose [-37.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-37.0 -6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkGreen"
   pose [-37.0 6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "aquamarine4"
   pose [-37.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "blue"
   pose [-37.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "cyan1"
   pose [-34.0 -23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "green"
   pose [-34.0 -11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "SeaGreen"
   pose [-34.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-34.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "VioletRed1"
   pose [-34.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "maroon4"
   pose [-34.0 23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "VioletRed1"
   pose [-31.0 -23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-31.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [-31.0 -6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "green"
   pose [-31.0 6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "VioletRed1"
   pose [-31.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrchid1"
   pose [-31.0 23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "magenta1"
   pose [-28.0 -23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "cyan1"
   pose [-28.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "aquamarine4"
   pose [-28.0 -6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkBlue"
   pose [-28.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "pink1"
   pose [-28.0 11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-28.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "pink1"
   pose [-25.0 -23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "maroon1"
   pose [-25.0 -11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkCyan"
   pose [-25.0 -6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "aquamarine4"
   pose [-25.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "aquamarine4"
   pose [-25.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "cyan1"
   pose [-25.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "green"
   pose [-22.0 -23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "blue"
   pose [-22.0 -11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkGreen"
   pose [-22.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkGreen"
   pose [-22.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "green"
   pose [-22.0 11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-22.0 23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkSlateGray"
   pose [-19.0 -23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-19.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "blue"
   pose [-19.0 -6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkBlue"
   pose [-19.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrchid1"
   pose [-19.0 11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "green"
   pose [-19.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-16.0 -23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "cyan1"
   pose [-16.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkMagenta"
   pose [-16.0 -6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-16.0 6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "turquoise1"
   pose [-16.0 11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkSlateGray"
   pose [-16.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "aquamarine4"
   pose [-13.0 -23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkBlue"
   pose [-13.0 -11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkMagenta"
   pose [-13.0 -6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkGreen"
   pose [-13.0 6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "navy"
   pose [-13.0 11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "blue"
   pose [-13.0 23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkOrchid1"
   pose [-10.0 -23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "maroon4"
   pose [-10.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "magenta1"
   pose [-10.0 -6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "maroon4"
   pose [-10.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [-10.0 11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "SteelBlue1"
   pose [-10.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "navy"
   pose [-7.0 -23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-7.0 -11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "pink1"
   pose [-7.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "aquamarine4"
   pose [-7.0 6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "navy"
   pose [-7.0 11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "SeaGreen"
   pose [-7.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "navy"
   pose [-4.0 -23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkOrange"
   pose [-4.0 -11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "cyan1"
   pose [-4.0 -6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkOrchid1"
   pose [-4.0 6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkRed"
   pose [-4.0 11.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "maroon1"
   pose [-4.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkCyan"
   pose [-1.0 -23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkRed"
   pose [-1.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-1.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkBlue"
   pose [-1.0 6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "magenta1"
   pose [-1.0 11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "SteelBlue1"
   pose [-1.0 23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkBlue"
   pose [2.0 -23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [2.0 -11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkOrchid1"
   pose [2.0 -6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "turquoise1"
   pose [2.0 6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "red"
   pose [2.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "pink1"
   pose [2.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "chocolate1"
   pose [5.0 -23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkBlue"
   pose [5.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "maroon1"
   pose [5.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkRed"
   pose [5.0 6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "SeaGreen"
   pose [5.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "green"
   pose [5.0 23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "cyan1"
   pose [8.0 -23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [8.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "cyan1"
   pose [8.0 -6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "maroon1"
   pose [8.0 6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "chocolate1"
   pose [8.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "aquamarine4"
   pose [8.0 23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DeepSkyBlue1"
   pose [11.0 -23.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "navy"
   pose [11.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkRed"
   pose [11.0 -6.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkSlateGray"
   pose [11.0 6.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "cyan1"
   pose [11.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "navy"
   pose [11.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "magenta1"
   pose [14.0 -23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "magenta1"
   pose [14.0 -11.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "maroon4"
   pose [14.0 -6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "magenta1"
   pose [14.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkGreen"
   pose [14.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "cyan1"
   pose [14.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkRed"
   pose [17.0 -23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "maroon1"
   pose [17.0 -11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "chocolate1"
   pose [17.0 -6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkMagenta"
   pose [17.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DeepSkyBlue1"
   pose [17.0 11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkMagenta"
   pose [17.0 23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [20.0 -23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "pink1"
   pose [20.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "magenta1"
   pose [20.0 -6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkGreen"
   pose [20.0 6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "chocolate1"
   pose [20.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkOrange"
   pose [20.0 23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "pink1"
   pose [23.0 -23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkSlateGray"
   pose [23.0 -11.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkMagenta"
   pose [23.0 -6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkBlue"
   pose [23.0 6.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "DarkGreen"
   pose [23.0 11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkMagenta"
   pose [23.0 23.0 0.0]
   bitmap "../../cars/car1.png"
)

car (
   color "magenta1"
   pose [26.0 -23.0 0.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkOrange"
   pose [26.0 -11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "aquamarine4"
   pose [26.0 -6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DeepSkyBlue1"
   pose [26.0 6.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkGreen"
   pose [26.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "chocolate1"
   pose [26.0 23.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "DarkMagenta"
   pose [29.0 -23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "SeaGreen"
   pose [29.0 -11.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkCyan"
   pose [29.0 -6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "DarkGreen"
   pose [29.0 6.0 0.0]
   bitmap "../../cars/car3.png"
)

car (
   color "aquamarine4"
   pose [29.0 11.0 0.0]
   bitmap "../../cars/car4.png"
)

car (
   color "SteelBlue1"
   pose [29.0 23.0 0.0]
   bitmap "../../cars/car5.png"
)

car (
   color "SeaGreen"
   pose [41.0 -14.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrange"
   pose [41.0 -11.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "turquoise1"
   pose [41.0 -8.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "black"
   pose [41.0 -5.0 -90.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkOrange"
   pose [41.0 -2.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkOrchid1"
   pose [41.0 1.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "DarkRed"
   pose [41.0 4.0 -90.0]
   bitmap "../../cars/car2.png"
)

car (
   color "DarkCyan"
   pose [41.0 7.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "navy"
   pose [41.0 10.0 -90.0]
   bitmap "../../cars/car2.png"
)

car (
   color "blue"
   pose [41.0 13.0 -90.0]
   bitmap "../../cars/car5.png"
)

car (
   color "red"
   pose [41.0 16.0 -90.0]
   bitmap "../../cars/car1.png"
)

car (
   color "blue"
   pose [41.0 19.0 -90.0]
   bitmap "../../cars/car4.png"
)

car (
   color "cyan1"
   pose [41.0 22.0 -90.0]
   bitmap "../../cars/car5.png"
)

